// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgApi.Data;

#nullable disable

namespace RpgApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260408005339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<int>("Defesa")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PontosVida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_PERSONAGENS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classe = 1,
                            Defesa = 23,
                            Forca = 17,
                            Inteligencia = 33,
                            Nome = "Frodo",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 2,
                            Classe = 1,
                            Defesa = 25,
                            Forca = 15,
                            Inteligencia = 30,
                            Nome = "Sam",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 3,
                            Classe = 1,
                            Defesa = 17,
                            Forca = 20,
                            Inteligencia = 31,
                            Nome = "Hobbit",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 4,
                            Classe = 1,
                            Defesa = 35,
                            Forca = 28,
                            Inteligencia = 25,
                            Nome = "Artur",
                            PontosVida = 120
                        },
                        new
                        {
                            Id = 5,
                            Classe = 1,
                            Defesa = 32,
                            Forca = 30,
                            Inteligencia = 24,
                            Nome = "Lancelote",
                            PontosVida = 115
                        },
                        new
                        {
                            Id = 6,
                            Classe = 1,
                            Defesa = 30,
                            Forca = 26,
                            Inteligencia = 22,
                            Nome = "Gawain",
                            PontosVida = 125
                        },
                        new
                        {
                            Id = 7,
                            Classe = 1,
                            Defesa = 28,
                            Forca = 25,
                            Inteligencia = 26,
                            Nome = "Bedivere",
                            PontosVida = 110
                        },
                        new
                        {
                            Id = 8,
                            Classe = 2,
                            Defesa = 18,
                            Forca = 18,
                            Inteligencia = 37,
                            Nome = "Gandalf",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 9,
                            Classe = 2,
                            Defesa = 15,
                            Forca = 14,
                            Inteligencia = 45,
                            Nome = "Merlin",
                            PontosVida = 85
                        },
                        new
                        {
                            Id = 10,
                            Classe = 2,
                            Defesa = 14,
                            Forca = 16,
                            Inteligencia = 48,
                            Nome = "Saruman",
                            PontosVida = 90
                        },
                        new
                        {
                            Id = 11,
                            Classe = 2,
                            Defesa = 16,
                            Forca = 13,
                            Inteligencia = 50,
                            Nome = "Morgana",
                            PontosVida = 88
                        },
                        new
                        {
                            Id = 12,
                            Classe = 2,
                            Defesa = 13,
                            Forca = 15,
                            Inteligencia = 42,
                            Nome = "Radagast",
                            PontosVida = 92
                        },
                        new
                        {
                            Id = 13,
                            Classe = 3,
                            Defesa = 21,
                            Forca = 18,
                            Inteligencia = 35,
                            Nome = "Galadriel",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 14,
                            Classe = 3,
                            Defesa = 13,
                            Forca = 21,
                            Inteligencia = 34,
                            Nome = "Celeborn",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 15,
                            Classe = 3,
                            Defesa = 24,
                            Forca = 18,
                            Inteligencia = 40,
                            Nome = "Elara",
                            PontosVida = 105
                        },
                        new
                        {
                            Id = 16,
                            Classe = 3,
                            Defesa = 26,
                            Forca = 16,
                            Inteligencia = 38,
                            Nome = "Isolda",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 17,
                            Classe = 3,
                            Defesa = 22,
                            Forca = 17,
                            Inteligencia = 41,
                            Nome = "Taliesin",
                            PontosVida = 102
                        },
                        new
                        {
                            Id = 18,
                            Classe = 3,
                            Defesa = 25,
                            Forca = 19,
                            Inteligencia = 39,
                            Nome = "Morgaine",
                            PontosVida = 108
                        },
                        new
                        {
                            Id = 19,
                            Classe = 4,
                            Defesa = 100,
                            Forca = 32,
                            Inteligencia = 80,
                            Nome = "Karsen",
                            PontosVida = 110
                        },
                        new
                        {
                            Id = 20,
                            Classe = 4,
                            Defesa = 20,
                            Forca = 35,
                            Inteligencia = 18,
                            Nome = "Conan",
                            PontosVida = 130
                        },
                        new
                        {
                            Id = 21,
                            Classe = 4,
                            Defesa = 22,
                            Forca = 33,
                            Inteligencia = 19,
                            Nome = "Beowulf",
                            PontosVida = 128
                        },
                        new
                        {
                            Id = 22,
                            Classe = 4,
                            Defesa = 24,
                            Forca = 31,
                            Inteligencia = 20,
                            Nome = "Sigurd",
                            PontosVida = 125
                        },
                        new
                        {
                            Id = 23,
                            Classe = 4,
                            Defesa = 19,
                            Forca = 36,
                            Inteligencia = 17,
                            Nome = "Heracles",
                            PontosVida = 135
                        },
                        new
                        {
                            Id = 24,
                            Classe = 5,
                            Defesa = 18,
                            Forca = 19,
                            Inteligencia = 35,
                            Nome = "Robin",
                            PontosVida = 95
                        },
                        new
                        {
                            Id = 25,
                            Classe = 5,
                            Defesa = 20,
                            Forca = 15,
                            Inteligencia = 60,
                            Nome = "Sofiz",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 26,
                            Classe = 5,
                            Defesa = 16,
                            Forca = 21,
                            Inteligencia = 32,
                            Nome = "Legolas",
                            PontosVida = 98
                        },
                        new
                        {
                            Id = 27,
                            Classe = 5,
                            Defesa = 17,
                            Forca = 20,
                            Inteligencia = 38,
                            Nome = "Artemis",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 28,
                            Classe = 5,
                            Defesa = 19,
                            Forca = 18,
                            Inteligencia = 36,
                            Nome = "Hawkeye",
                            PontosVida = 93
                        },
                        new
                        {
                            Id = 29,
                            Classe = 5,
                            Defesa = 15,
                            Forca = 22,
                            Inteligencia = 34,
                            Nome = "Darthur",
                            PontosVida = 96
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
