// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgApi.Data;

#nullable disable

namespace RpgApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260505234111_MigracaoMuitosParaMuitos")]
    partial class MigracaoMuitosParaMuitos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RpgAPI.Models.Arma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dano")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId")
                        .IsUnique();

                    b.ToTable("TB_ARMAS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dano = 48,
                            Nome = "Espada Kaos",
                            PersonagemId = 1
                        },
                        new
                        {
                            Id = 2,
                            Dano = 21,
                            Nome = "Arco iNOE",
                            PersonagemId = 4
                        },
                        new
                        {
                            Id = 3,
                            Dano = 69,
                            Nome = "Adaga Heian",
                            PersonagemId = 8
                        },
                        new
                        {
                            Id = 4,
                            Dano = 2,
                            Nome = "Amuleto KoIs Amaldiçoado",
                            PersonagemId = 2
                        },
                        new
                        {
                            Id = 5,
                            Dano = 12,
                            Nome = "Olhos ReinKiri",
                            PersonagemId = 7
                        });
                });

            modelBuilder.Entity("RpgAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasDefaultValue("Player");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "seuEmail@email.com",
                            Latitude = -23.520024100000001,
                            Longitude = -56.596497999999997,
                            PasswordHash = new byte[] { 114, 183, 59, 130, 96, 106, 125, 95, 178, 168, 31, 14, 170, 1, 181, 110, 9, 212, 203, 55, 27, 102, 224, 108, 216, 73, 187, 220, 129, 112, 47, 2, 183, 126, 11, 116, 168, 85, 191, 2, 40, 104, 185, 249, 193, 166, 0, 162, 155, 253, 48, 235, 5, 204, 156, 223, 221, 35, 225, 228, 5, 30, 249, 238 },
                            PasswordSalt = new byte[] { 48, 153, 3, 153, 148, 100, 252, 135, 96, 26, 61, 216, 42, 43, 146, 148, 106, 42, 102, 103, 138, 96, 136, 4, 237, 88, 60, 90, 144, 174, 117, 146, 135, 187, 94, 233, 91, 57, 243, 29, 89, 192, 137, 46, 18, 77, 1, 181, 81, 77, 15, 205, 156, 213, 36, 57, 95, 194, 22, 7, 64, 31, 120, 121, 70, 1, 110, 69, 227, 74, 135, 119, 31, 19, 152, 128, 188, 114, 28, 194, 111, 207, 116, 98, 181, 73, 20, 31, 163, 123, 236, 152, 250, 180, 214, 181, 82, 185, 206, 122, 65, 3, 12, 223, 71, 94, 15, 224, 58, 9, 89, 50, 248, 181, 123, 121, 195, 238, 75, 222, 136, 176, 110, 228, 62, 7, 26, 59 },
                            Perfil = "admin",
                            Username = "UsuarioAdmin"
                        });
                });

            modelBuilder.Entity("RpgApi.Models.Habilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dano")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_HABILIDADES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dano = 23,
                            Nome = "Fogo amaldiçoado"
                        },
                        new
                        {
                            Id = 2,
                            Dano = 67,
                            Nome = "Chuva ContraTempoária"
                        },
                        new
                        {
                            Id = 3,
                            Dano = 16,
                            Nome = "Corte Simples | Novo estilo da Sombra"
                        },
                        new
                        {
                            Id = 4,
                            Dano = 0,
                            Nome = "Gás Tóxico | MicroFissura"
                        },
                        new
                        {
                            Id = 5,
                            Dano = 0,
                            Nome = "Pico de força Espartana"
                        },
                        new
                        {
                            Id = 6,
                            Dano = 0,
                            Nome = "Anomalia Temporal"
                        });
                });

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<int>("Defesa")
                        .HasColumnType("int");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<int>("Disputas")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoPersoangem")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PontosVida")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_PERSONAGENS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classe = 1,
                            Defesa = 23,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 17,
                            Inteligencia = 33,
                            Nome = "Frodo",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 2,
                            Classe = 1,
                            Defesa = 25,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 15,
                            Inteligencia = 30,
                            Nome = "Sam",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 3,
                            Classe = 1,
                            Defesa = 17,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 20,
                            Inteligencia = 31,
                            Nome = "Hobbit",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 4,
                            Classe = 1,
                            Defesa = 35,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 28,
                            Inteligencia = 25,
                            Nome = "Artur",
                            PontosVida = 120,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 5,
                            Classe = 1,
                            Defesa = 32,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 30,
                            Inteligencia = 24,
                            Nome = "Lancelote",
                            PontosVida = 115,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 6,
                            Classe = 1,
                            Defesa = 30,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 26,
                            Inteligencia = 22,
                            Nome = "Gawain",
                            PontosVida = 125,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 7,
                            Classe = 1,
                            Defesa = 28,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 25,
                            Inteligencia = 26,
                            Nome = "Bedivere",
                            PontosVida = 110,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 8,
                            Classe = 2,
                            Defesa = 18,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 18,
                            Inteligencia = 37,
                            Nome = "Gandalf",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 9,
                            Classe = 2,
                            Defesa = 15,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 14,
                            Inteligencia = 45,
                            Nome = "Merlin",
                            PontosVida = 85,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 10,
                            Classe = 2,
                            Defesa = 14,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 16,
                            Inteligencia = 48,
                            Nome = "Saruman",
                            PontosVida = 90,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 11,
                            Classe = 2,
                            Defesa = 16,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 13,
                            Inteligencia = 50,
                            Nome = "Morgana",
                            PontosVida = 88,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 12,
                            Classe = 2,
                            Defesa = 13,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 15,
                            Inteligencia = 42,
                            Nome = "Radagast",
                            PontosVida = 92,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 13,
                            Classe = 3,
                            Defesa = 21,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 18,
                            Inteligencia = 35,
                            Nome = "Galadriel",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 14,
                            Classe = 3,
                            Defesa = 13,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 21,
                            Inteligencia = 34,
                            Nome = "Celeborn",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 15,
                            Classe = 3,
                            Defesa = 24,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 18,
                            Inteligencia = 40,
                            Nome = "Elara",
                            PontosVida = 105,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 16,
                            Classe = 3,
                            Defesa = 26,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 16,
                            Inteligencia = 38,
                            Nome = "Isolda",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 17,
                            Classe = 3,
                            Defesa = 22,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 17,
                            Inteligencia = 41,
                            Nome = "Taliesin",
                            PontosVida = 102,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 18,
                            Classe = 3,
                            Defesa = 25,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 19,
                            Inteligencia = 39,
                            Nome = "Morgaine",
                            PontosVida = 108,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 19,
                            Classe = 4,
                            Defesa = 100,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 32,
                            Inteligencia = 80,
                            Nome = "Karsen",
                            PontosVida = 110,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 20,
                            Classe = 4,
                            Defesa = 20,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 35,
                            Inteligencia = 18,
                            Nome = "Conan",
                            PontosVida = 130,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 21,
                            Classe = 4,
                            Defesa = 22,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 33,
                            Inteligencia = 19,
                            Nome = "Beowulf",
                            PontosVida = 128,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 22,
                            Classe = 4,
                            Defesa = 24,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 31,
                            Inteligencia = 20,
                            Nome = "Sigurd",
                            PontosVida = 125,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 23,
                            Classe = 4,
                            Defesa = 19,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 36,
                            Inteligencia = 17,
                            Nome = "Heracles",
                            PontosVida = 135,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 24,
                            Classe = 5,
                            Defesa = 18,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 19,
                            Inteligencia = 35,
                            Nome = "Robin",
                            PontosVida = 95,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 25,
                            Classe = 5,
                            Defesa = 20,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 15,
                            Inteligencia = 60,
                            Nome = "Sofiz",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 26,
                            Classe = 5,
                            Defesa = 16,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 21,
                            Inteligencia = 32,
                            Nome = "Legolas",
                            PontosVida = 98,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 27,
                            Classe = 5,
                            Defesa = 17,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 20,
                            Inteligencia = 38,
                            Nome = "Artemis",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 28,
                            Classe = 5,
                            Defesa = 19,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 18,
                            Inteligencia = 36,
                            Nome = "Hawkeye",
                            PontosVida = 93,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 29,
                            Classe = 5,
                            Defesa = 15,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 22,
                            Inteligencia = 34,
                            Nome = "Darthur",
                            PontosVida = 96,
                            UsuarioId = 1,
                            Vitorias = 0
                        });
                });

            modelBuilder.Entity("RpgApi.Models.PersonagemHabilidade", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("HabilidadeId")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId", "HabilidadeId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("TB_PERSONAGENS_HABILIDADES", (string)null);

                    b.HasData(
                        new
                        {
                            PersonagemId = 1,
                            HabilidadeId = 2
                        },
                        new
                        {
                            PersonagemId = 1,
                            HabilidadeId = 1
                        },
                        new
                        {
                            PersonagemId = 1,
                            HabilidadeId = 3
                        },
                        new
                        {
                            PersonagemId = 1,
                            HabilidadeId = 4
                        },
                        new
                        {
                            PersonagemId = 1,
                            HabilidadeId = 5
                        },
                        new
                        {
                            PersonagemId = 2,
                            HabilidadeId = 1
                        },
                        new
                        {
                            PersonagemId = 2,
                            HabilidadeId = 3
                        },
                        new
                        {
                            PersonagemId = 3,
                            HabilidadeId = 1
                        },
                        new
                        {
                            PersonagemId = 3,
                            HabilidadeId = 3
                        },
                        new
                        {
                            PersonagemId = 3,
                            HabilidadeId = 2
                        },
                        new
                        {
                            PersonagemId = 4,
                            HabilidadeId = 5
                        },
                        new
                        {
                            PersonagemId = 5,
                            HabilidadeId = 1
                        },
                        new
                        {
                            PersonagemId = 5,
                            HabilidadeId = 2
                        },
                        new
                        {
                            PersonagemId = 5,
                            HabilidadeId = 4
                        });
                });

            modelBuilder.Entity("RpgAPI.Models.Arma", b =>
                {
                    b.HasOne("RpgApi.Models.Personagem", "Personagem")
                        .WithOne("Arma")
                        .HasForeignKey("RpgAPI.Models.Arma", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.HasOne("RpgAPI.Models.Usuario", "Usuario")
                        .WithMany("Personagens")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RpgApi.Models.PersonagemHabilidade", b =>
                {
                    b.HasOne("RpgApi.Models.Habilidade", "Habilidade")
                        .WithMany("PersonagemHabilidades")
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgApi.Models.Personagem", "Personagem")
                        .WithMany()
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("RpgAPI.Models.Usuario", b =>
                {
                    b.Navigation("Personagens");
                });

            modelBuilder.Entity("RpgApi.Models.Habilidade", b =>
                {
                    b.Navigation("PersonagemHabilidades");
                });

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.Navigation("Arma");
                });
#pragma warning restore 612, 618
        }
    }
}
