// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgApi.Data;

#nullable disable

namespace RpgApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260429012946_MigracaoUsuario")]
    partial class MigracaoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RpgAPI.Models.Arma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dano")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_ARMAS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dano = 48,
                            Nome = "Espada Kaos"
                        },
                        new
                        {
                            Id = 2,
                            Dano = 21,
                            Nome = "Arco iNOE"
                        },
                        new
                        {
                            Id = 3,
                            Dano = 69,
                            Nome = "Adaga Heian"
                        },
                        new
                        {
                            Id = 4,
                            Dano = 2,
                            Nome = "Amuleto KoIs Amaldiçoado"
                        },
                        new
                        {
                            Id = 5,
                            Dano = 12,
                            Nome = "Olhos ReinKiri"
                        });
                });

            modelBuilder.Entity("RpgAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasDefaultValue("Player");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "seuEmail@email.com",
                            Latitude = -23.520024100000001,
                            Longitude = -56.596497999999997,
                            PasswordHash = new byte[] { 27, 47, 174, 11, 243, 180, 199, 113, 19, 132, 63, 30, 137, 224, 176, 24, 42, 49, 186, 144, 138, 100, 168, 204, 120, 32, 17, 41, 12, 4, 77, 17, 198, 231, 135, 174, 20, 224, 160, 69, 244, 212, 50, 36, 18, 162, 70, 191, 216, 174, 206, 56, 14, 205, 66, 247, 129, 27, 184, 214, 142, 115, 240, 236 },
                            PasswordSalt = new byte[] { 243, 239, 121, 206, 98, 189, 55, 221, 131, 82, 113, 84, 46, 146, 170, 138, 73, 64, 223, 161, 217, 120, 142, 252, 48, 47, 227, 85, 116, 253, 249, 15, 35, 207, 234, 19, 52, 136, 128, 218, 211, 46, 39, 227, 97, 14, 206, 242, 2, 213, 255, 198, 101, 159, 6, 134, 134, 246, 139, 225, 99, 188, 108, 99, 91, 230, 156, 199, 137, 55, 77, 202, 19, 12, 132, 153, 17, 145, 244, 50, 150, 133, 206, 133, 17, 207, 178, 91, 87, 169, 197, 216, 5, 223, 252, 31, 78, 104, 110, 47, 76, 175, 60, 111, 170, 21, 63, 163, 6, 209, 225, 60, 229, 175, 47, 154, 84, 247, 122, 142, 138, 208, 5, 131, 236, 80, 92, 180 },
                            Perfil = "admin",
                            Username = "UsuarioAdmin"
                        });
                });

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<int>("Defesa")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoPersoangem")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PontosVida")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_PERSONAGENS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classe = 1,
                            Defesa = 23,
                            Forca = 17,
                            Inteligencia = 33,
                            Nome = "Frodo",
                            PontosVida = 100,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Classe = 1,
                            Defesa = 25,
                            Forca = 15,
                            Inteligencia = 30,
                            Nome = "Sam",
                            PontosVida = 100,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 3,
                            Classe = 1,
                            Defesa = 17,
                            Forca = 20,
                            Inteligencia = 31,
                            Nome = "Hobbit",
                            PontosVida = 100,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 4,
                            Classe = 1,
                            Defesa = 35,
                            Forca = 28,
                            Inteligencia = 25,
                            Nome = "Artur",
                            PontosVida = 120,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 5,
                            Classe = 1,
                            Defesa = 32,
                            Forca = 30,
                            Inteligencia = 24,
                            Nome = "Lancelote",
                            PontosVida = 115,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 6,
                            Classe = 1,
                            Defesa = 30,
                            Forca = 26,
                            Inteligencia = 22,
                            Nome = "Gawain",
                            PontosVida = 125,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 7,
                            Classe = 1,
                            Defesa = 28,
                            Forca = 25,
                            Inteligencia = 26,
                            Nome = "Bedivere",
                            PontosVida = 110,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 8,
                            Classe = 2,
                            Defesa = 18,
                            Forca = 18,
                            Inteligencia = 37,
                            Nome = "Gandalf",
                            PontosVida = 100,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 9,
                            Classe = 2,
                            Defesa = 15,
                            Forca = 14,
                            Inteligencia = 45,
                            Nome = "Merlin",
                            PontosVida = 85,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 10,
                            Classe = 2,
                            Defesa = 14,
                            Forca = 16,
                            Inteligencia = 48,
                            Nome = "Saruman",
                            PontosVida = 90,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 11,
                            Classe = 2,
                            Defesa = 16,
                            Forca = 13,
                            Inteligencia = 50,
                            Nome = "Morgana",
                            PontosVida = 88,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 12,
                            Classe = 2,
                            Defesa = 13,
                            Forca = 15,
                            Inteligencia = 42,
                            Nome = "Radagast",
                            PontosVida = 92,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 13,
                            Classe = 3,
                            Defesa = 21,
                            Forca = 18,
                            Inteligencia = 35,
                            Nome = "Galadriel",
                            PontosVida = 100,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 14,
                            Classe = 3,
                            Defesa = 13,
                            Forca = 21,
                            Inteligencia = 34,
                            Nome = "Celeborn",
                            PontosVida = 100,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 15,
                            Classe = 3,
                            Defesa = 24,
                            Forca = 18,
                            Inteligencia = 40,
                            Nome = "Elara",
                            PontosVida = 105,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 16,
                            Classe = 3,
                            Defesa = 26,
                            Forca = 16,
                            Inteligencia = 38,
                            Nome = "Isolda",
                            PontosVida = 100,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 17,
                            Classe = 3,
                            Defesa = 22,
                            Forca = 17,
                            Inteligencia = 41,
                            Nome = "Taliesin",
                            PontosVida = 102,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 18,
                            Classe = 3,
                            Defesa = 25,
                            Forca = 19,
                            Inteligencia = 39,
                            Nome = "Morgaine",
                            PontosVida = 108,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 19,
                            Classe = 4,
                            Defesa = 100,
                            Forca = 32,
                            Inteligencia = 80,
                            Nome = "Karsen",
                            PontosVida = 110,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 20,
                            Classe = 4,
                            Defesa = 20,
                            Forca = 35,
                            Inteligencia = 18,
                            Nome = "Conan",
                            PontosVida = 130,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 21,
                            Classe = 4,
                            Defesa = 22,
                            Forca = 33,
                            Inteligencia = 19,
                            Nome = "Beowulf",
                            PontosVida = 128,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 22,
                            Classe = 4,
                            Defesa = 24,
                            Forca = 31,
                            Inteligencia = 20,
                            Nome = "Sigurd",
                            PontosVida = 125,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 23,
                            Classe = 4,
                            Defesa = 19,
                            Forca = 36,
                            Inteligencia = 17,
                            Nome = "Heracles",
                            PontosVida = 135,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 24,
                            Classe = 5,
                            Defesa = 18,
                            Forca = 19,
                            Inteligencia = 35,
                            Nome = "Robin",
                            PontosVida = 95,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 25,
                            Classe = 5,
                            Defesa = 20,
                            Forca = 15,
                            Inteligencia = 60,
                            Nome = "Sofiz",
                            PontosVida = 100,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 26,
                            Classe = 5,
                            Defesa = 16,
                            Forca = 21,
                            Inteligencia = 32,
                            Nome = "Legolas",
                            PontosVida = 98,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 27,
                            Classe = 5,
                            Defesa = 17,
                            Forca = 20,
                            Inteligencia = 38,
                            Nome = "Artemis",
                            PontosVida = 100,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 28,
                            Classe = 5,
                            Defesa = 19,
                            Forca = 18,
                            Inteligencia = 36,
                            Nome = "Hawkeye",
                            PontosVida = 93,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 29,
                            Classe = 5,
                            Defesa = 15,
                            Forca = 22,
                            Inteligencia = 34,
                            Nome = "Darthur",
                            PontosVida = 96,
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.HasOne("RpgAPI.Models.Usuario", "Usuario")
                        .WithMany("Personagens")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RpgAPI.Models.Usuario", b =>
                {
                    b.Navigation("Personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
