// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgApi.Data;

#nullable disable

namespace RpgApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260505230935_MigracaoUmParaUm")]
    partial class MigracaoUmParaUm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RpgAPI.Models.Arma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dano")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId")
                        .IsUnique();

                    b.ToTable("TB_ARMAS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dano = 48,
                            Nome = "Espada Kaos",
                            PersonagemId = 1
                        },
                        new
                        {
                            Id = 2,
                            Dano = 21,
                            Nome = "Arco iNOE",
                            PersonagemId = 4
                        },
                        new
                        {
                            Id = 3,
                            Dano = 69,
                            Nome = "Adaga Heian",
                            PersonagemId = 8
                        },
                        new
                        {
                            Id = 4,
                            Dano = 2,
                            Nome = "Amuleto KoIs Amaldiçoado",
                            PersonagemId = 2
                        },
                        new
                        {
                            Id = 5,
                            Dano = 12,
                            Nome = "Olhos ReinKiri",
                            PersonagemId = 7
                        });
                });

            modelBuilder.Entity("RpgAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasDefaultValue("Player");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "seuEmail@email.com",
                            Latitude = -23.520024100000001,
                            Longitude = -56.596497999999997,
                            PasswordHash = new byte[] { 211, 23, 98, 185, 137, 120, 159, 97, 70, 166, 87, 109, 33, 246, 61, 203, 1, 74, 177, 92, 69, 0, 84, 172, 85, 11, 158, 31, 118, 144, 144, 55, 71, 126, 1, 117, 3, 163, 56, 88, 236, 8, 241, 5, 155, 194, 110, 142, 38, 190, 78, 75, 180, 74, 137, 144, 158, 247, 60, 16, 170, 107, 211, 3 },
                            PasswordSalt = new byte[] { 240, 246, 86, 163, 112, 115, 140, 33, 74, 65, 236, 240, 127, 152, 92, 76, 49, 0, 108, 194, 145, 169, 214, 62, 223, 203, 70, 242, 158, 3, 2, 129, 218, 206, 74, 103, 111, 231, 65, 90, 11, 57, 193, 241, 29, 213, 130, 111, 52, 164, 234, 216, 126, 120, 64, 58, 155, 27, 236, 155, 239, 67, 158, 19, 110, 113, 140, 7, 98, 214, 224, 23, 128, 32, 90, 249, 62, 41, 248, 176, 88, 2, 142, 20, 229, 35, 250, 21, 225, 163, 20, 0, 112, 142, 215, 75, 144, 98, 118, 45, 121, 159, 167, 166, 120, 187, 168, 4, 159, 206, 53, 44, 244, 116, 100, 72, 4, 45, 79, 194, 243, 124, 88, 128, 153, 210, 206, 249 },
                            Perfil = "admin",
                            Username = "UsuarioAdmin"
                        });
                });

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<int>("Defesa")
                        .HasColumnType("int");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<int>("Disputas")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoPersoangem")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PontosVida")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_PERSONAGENS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classe = 1,
                            Defesa = 23,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 17,
                            Inteligencia = 33,
                            Nome = "Frodo",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 2,
                            Classe = 1,
                            Defesa = 25,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 15,
                            Inteligencia = 30,
                            Nome = "Sam",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 3,
                            Classe = 1,
                            Defesa = 17,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 20,
                            Inteligencia = 31,
                            Nome = "Hobbit",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 4,
                            Classe = 1,
                            Defesa = 35,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 28,
                            Inteligencia = 25,
                            Nome = "Artur",
                            PontosVida = 120,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 5,
                            Classe = 1,
                            Defesa = 32,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 30,
                            Inteligencia = 24,
                            Nome = "Lancelote",
                            PontosVida = 115,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 6,
                            Classe = 1,
                            Defesa = 30,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 26,
                            Inteligencia = 22,
                            Nome = "Gawain",
                            PontosVida = 125,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 7,
                            Classe = 1,
                            Defesa = 28,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 25,
                            Inteligencia = 26,
                            Nome = "Bedivere",
                            PontosVida = 110,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 8,
                            Classe = 2,
                            Defesa = 18,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 18,
                            Inteligencia = 37,
                            Nome = "Gandalf",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 9,
                            Classe = 2,
                            Defesa = 15,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 14,
                            Inteligencia = 45,
                            Nome = "Merlin",
                            PontosVida = 85,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 10,
                            Classe = 2,
                            Defesa = 14,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 16,
                            Inteligencia = 48,
                            Nome = "Saruman",
                            PontosVida = 90,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 11,
                            Classe = 2,
                            Defesa = 16,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 13,
                            Inteligencia = 50,
                            Nome = "Morgana",
                            PontosVida = 88,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 12,
                            Classe = 2,
                            Defesa = 13,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 15,
                            Inteligencia = 42,
                            Nome = "Radagast",
                            PontosVida = 92,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 13,
                            Classe = 3,
                            Defesa = 21,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 18,
                            Inteligencia = 35,
                            Nome = "Galadriel",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 14,
                            Classe = 3,
                            Defesa = 13,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 21,
                            Inteligencia = 34,
                            Nome = "Celeborn",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 15,
                            Classe = 3,
                            Defesa = 24,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 18,
                            Inteligencia = 40,
                            Nome = "Elara",
                            PontosVida = 105,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 16,
                            Classe = 3,
                            Defesa = 26,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 16,
                            Inteligencia = 38,
                            Nome = "Isolda",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 17,
                            Classe = 3,
                            Defesa = 22,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 17,
                            Inteligencia = 41,
                            Nome = "Taliesin",
                            PontosVida = 102,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 18,
                            Classe = 3,
                            Defesa = 25,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 19,
                            Inteligencia = 39,
                            Nome = "Morgaine",
                            PontosVida = 108,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 19,
                            Classe = 4,
                            Defesa = 100,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 32,
                            Inteligencia = 80,
                            Nome = "Karsen",
                            PontosVida = 110,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 20,
                            Classe = 4,
                            Defesa = 20,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 35,
                            Inteligencia = 18,
                            Nome = "Conan",
                            PontosVida = 130,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 21,
                            Classe = 4,
                            Defesa = 22,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 33,
                            Inteligencia = 19,
                            Nome = "Beowulf",
                            PontosVida = 128,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 22,
                            Classe = 4,
                            Defesa = 24,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 31,
                            Inteligencia = 20,
                            Nome = "Sigurd",
                            PontosVida = 125,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 23,
                            Classe = 4,
                            Defesa = 19,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 36,
                            Inteligencia = 17,
                            Nome = "Heracles",
                            PontosVida = 135,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 24,
                            Classe = 5,
                            Defesa = 18,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 19,
                            Inteligencia = 35,
                            Nome = "Robin",
                            PontosVida = 95,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 25,
                            Classe = 5,
                            Defesa = 20,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 15,
                            Inteligencia = 60,
                            Nome = "Sofiz",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 26,
                            Classe = 5,
                            Defesa = 16,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 21,
                            Inteligencia = 32,
                            Nome = "Legolas",
                            PontosVida = 98,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 27,
                            Classe = 5,
                            Defesa = 17,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 20,
                            Inteligencia = 38,
                            Nome = "Artemis",
                            PontosVida = 100,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 28,
                            Classe = 5,
                            Defesa = 19,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 18,
                            Inteligencia = 36,
                            Nome = "Hawkeye",
                            PontosVida = 93,
                            UsuarioId = 1,
                            Vitorias = 0
                        },
                        new
                        {
                            Id = 29,
                            Classe = 5,
                            Defesa = 15,
                            Derrotas = 0,
                            Disputas = 0,
                            Forca = 22,
                            Inteligencia = 34,
                            Nome = "Darthur",
                            PontosVida = 96,
                            UsuarioId = 1,
                            Vitorias = 0
                        });
                });

            modelBuilder.Entity("RpgAPI.Models.Arma", b =>
                {
                    b.HasOne("RpgApi.Models.Personagem", "Personagem")
                        .WithOne("Arma")
                        .HasForeignKey("RpgAPI.Models.Arma", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.HasOne("RpgAPI.Models.Usuario", "Usuario")
                        .WithMany("Personagens")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RpgAPI.Models.Usuario", b =>
                {
                    b.Navigation("Personagens");
                });

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.Navigation("Arma");
                });
#pragma warning restore 612, 618
        }
    }
}
